# backend/app/integrations/object_storage.py
"""Object-storage port (S3/MinIO in production, in-memory fake in tests).

Object keys are always server-generated by the adapter, never built from
untrusted path fragments (docs/architecture/interfaces.md, Adapter Ports;
docs/quality/backend-engineering.md §16): the canonical V1 shape is
`submissions/{claim_id}/{uuid}` and the original filename is display
metadata only. No provider SDK is imported here; a real S3 adapter is a
separate later task.
"""

from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID


@dataclass(frozen=True)
class UploadUrl:
    """A short-lived presigned upload target for one server-generated key."""

    object_key: str
    url: str
    expires_at: datetime


@dataclass(frozen=True)
class ObjectHead:
    """Existence and content metadata for one stored object."""

    object_key: str
    size: int
    content_type: str


@dataclass(frozen=True)
class DownloadUrl:
    """A short-lived signed download URL for one existing key."""

    object_key: str
    url: str
    expires_at: datetime


class ObjectStorage(Protocol):
    """Port for presigned uploads, metadata checks, and signed downloads."""

    def create_upload_url(
        self, *, claim_id: UUID, content_type: str, expires_in: timedelta
    ) -> UploadUrl:
        """Issue a short-lived presigned PUT and return it with its key.

        Args:
            claim_id: Claim the upload belongs to; the adapter derives the
                server-generated key `submissions/{claim_id}/{uuid}` from it
                and the caller persists exactly the returned key.
            content_type: Declared MIME type pinned on the presigned URL; a
                client PUT with a different Content-Type is rejected by the
                provider.
            expires_in: Time-to-live of the URL; keep it short (minutes) —
                the returned `expires_at` is the instant it stops working.
        """
        ...

    def head_object(self, *, object_key: str) -> ObjectHead | None:
        """Return metadata for `object_key`, or `None` when it is missing.

        Args:
            object_key: Key previously returned by `create_upload_url`.
                A missing object is a normal result, not an error, so
                finalize and cleanup paths can distinguish "never uploaded"
                from a provider failure.
        """
        ...

    def create_download_url(
        self, *, object_key: str, expires_in: timedelta
    ) -> DownloadUrl:
        """Sign a short-lived GET for `object_key`.

        Args:
            object_key: Key previously returned by `create_upload_url`;
                callers must verify business authorization before signing
                (backend-engineering §16). Providers sign without checking
                existence, and so does every implementation of this port.
            expires_in: Time-to-live of the URL; keep it short (minutes) —
                the returned `expires_at` is the instant it stops working.
        """
        ...
