/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke exactly the presented session; clear the auth cookies.
         *
         *     Body optional for the same reason as refresh: cookie clients may send
         *     none.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description Reset OTP to the bound phone — uniformly for EVERY identifier class.
         *
         *     Known student, unknown username, staff account, phoneless student: the
         *     response is the identical challenge shape either way (no enumeration
         *     oracle; see ProfileService.request_password_reset).
         */
        post: operations["request_password_reset_api_v1_auth_password_forgot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Phone Challenge
         * @description Issue a REGISTER-purpose OTP challenge (spec §5.4, §33.2).
         *
         *     The purpose is fixed server-side: a public endpoint must never mint
         *     proofs for password reset or phone change.
         */
        post: operations["request_phone_challenge_api_v1_auth_phone_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/challenges/{challenge_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Phone Challenge
         * @description Consume the challenge with its SMS code; mint the single-use proof.
         */
        post: operations["verify_phone_challenge_api_v1_auth_phone_challenges__challenge_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate one refresh session (cookie or body token; spec §5.6).
         *
         *     The body is optional: a cookie-authenticated browser sends no body at
         *     all (the CSRF header carries the mutation proof), so requiring one
         *     would 422 the exact client this endpoint serves.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Student */
        post: operations["register_student_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Staff Invitation
         * @description Trade the single-use invitation token for a pending staff session.
         *
         *     The returned tokens are a real session confined to finishing TOTP
         *     setup (§5.8); management endpoints stay closed until 2FA is confirmed.
         */
        post: operations["accept_staff_invitation_api_v1_auth_staff_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/staff/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff Login
         * @description Staff login: verified email + password + TOTP-or-recovery (§5.8).
         *
         *     A correct password without a confirmed TOTP raises the typed setup
         *     error, rendered as 403 ``TOTP_SETUP_REQUIRED`` — the client's signal to
         *     finish ``/staff/totp/*`` first.
         */
        post: operations["staff_login_api_v1_auth_staff_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description The owner's own account view (spec §40). Read-only: any live session
         *     may read its own profile, including a suspended account's.
         */
        get: operations["read_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Claims
         * @description The actor's own claim history, newest first; assignment
         *     platform/keyword are visible here because every row is the owner's.
         *     A Student surface by policy (spec §4.1): staff never own claims, and
         *     the 403 pins that boundary instead of serving an empty list.
         */
        get: operations["list_my_claims_api_v1_me_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Email Verification */
        post: operations["request_email_verification_api_v1_me_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email/unbind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unbind Email */
        post: operations["unbind_email_api_v1_me_email_unbind_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Email Verification */
        post: operations["confirm_email_verification_api_v1_me_email_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Nickname */
        patch: operations["change_nickname_api_v1_me_nickname_patch"];
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Rotate the password; every other session dies, this one survives.
         */
        post: operations["change_password_api_v1_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/phone/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Phone Change
         * @description Re-authenticate, then OTP-challenge the NEW phone (spec §5.4).
         */
        post: operations["request_phone_change_api_v1_me_phone_change_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/phone/change/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Phone Change */
        post: operations["confirm_phone_change_api_v1_me_phone_change_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChallengeResponse
         * @description Request-side view of an OTP challenge (never the code, §33.2).
         */
        ChallengeResponse: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * EmailBindRequest
         * @description Bind (or re-bind) an email and send its verification token (§5.5).
         */
        EmailBindRequest: {
            /** Email */
            email: string;
        };
        /**
         * EmailChallengeResponse
         * @description Request-side view of one email-verification cycle (token-less).
         */
        EmailChallengeResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * EmailUnbindRequest
         * @description Unbind the email after re-authentication (spec §5.5).
         */
        EmailUnbindRequest: {
            /** Password */
            password: string;
        };
        /**
         * EmailVerifyRequest
         * @description Confirm an email binding with the token from the message (§5.5).
         */
        EmailVerifyRequest: {
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Student login: student number + password (spec §5.6).
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * LogoutRequest
         * @description Logout one session; cookie-carried tokens need no body.
         */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * MePublic
         * @description The owner's own account page (spec §40): contacts included.
         *
         *     Phone and email are the owner's own data (they typed them); the DTO
         *     still enumerates fields explicitly, so the Argon2id verifier and any
         *     other internal column stay unrepresentable.
         */
        MePublic: {
            /** Email Normalized */
            email_normalized: string | null;
            /** Email Verified At */
            email_verified_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            /** Phone E164 */
            phone_e164: string | null;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Username */
            username: string;
        };
        /**
         * MyClaimResponse
         * @description A /me/claims item: the claim view plus the task's title (the list is
         *     cross-task, so the card context travels with the claim).
         */
        MyClaimResponse: {
            /** Base Reward Points Snapshot */
            base_reward_points_snapshot: number;
            /**
             * Claim Id
             * Format: uuid
             */
            claim_id: string;
            /**
             * Claimed At
             * Format: date-time
             */
            claimed_at: string;
            /**
             * Deadline At
             * Format: date-time
             */
            deadline_at: string;
            /**
             * Grace Deadline At
             * Format: date-time
             */
            grace_deadline_at: string;
            /** Keyword */
            keyword: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Task Title */
            task_title: string;
        };
        /**
         * MyClaimsResponse
         * @description Offset-paginated own-claim history (current first).
         */
        MyClaimsResponse: {
            /** Items */
            items: components["schemas"]["MyClaimResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * NicknameUpdateRequest
         * @description Change the account nickname (spec §5.3).
         */
        NicknameUpdateRequest: {
            /** Nickname */
            nickname: string;
        };
        /**
         * PasswordChangeRequest
         * @description Rotate the password after re-authentication (spec §5.6).
         */
        PasswordChangeRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PasswordForgotRequest
         * @description Request a password-reset OTP on the bound phone (spec §5.6).
         */
        PasswordForgotRequest: {
            /** Username */
            username: string;
        };
        /**
         * PasswordResetRequest
         * @description Confirm a password reset with the OTP code and a new password.
         */
        PasswordResetRequest: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Code */
            code: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PhoneChallengeRequest
         * @description Request one registration OTP for ``phone`` (spec §5.4, §33.2).
         */
        PhoneChallengeRequest: {
            /** Phone */
            phone: string;
        };
        /**
         * PhoneChallengeVerifyRequest
         * @description Submit the SMS code for one challenge (spec §5.4).
         */
        PhoneChallengeVerifyRequest: {
            /** Code */
            code: string;
        };
        /**
         * PhoneChangeConfirmRequest
         * @description Confirm a phone change with the NEW phone's OTP code (spec §5.4).
         */
        PhoneChangeConfirmRequest: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Code */
            code: string;
        };
        /**
         * PhoneChangeRequest
         * @description Start a phone change: re-auth plus the NEW phone (spec §5.4).
         */
        PhoneChangeRequest: {
            /** New Phone */
            new_phone: string;
            /** Password */
            password: string;
        };
        /**
         * PhoneTokenResponse
         * @description The single-use proof minted by a verified challenge (spec §5.4).
         */
        PhoneTokenResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Phone Token */
            phone_token: string;
        };
        /**
         * RefreshRequest
         * @description Rotate one refresh session; the token may also arrive by cookie.
         *
         *     ``refresh_token`` is omitted by cookie-authenticated clients (the
         *     HttpOnly refresh cookie carries it); non-browser clients pass it here.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /**
         * RegisterRequest
         * @description Register one whitelisted student (spec §5.1-5.4).
         */
        RegisterRequest: {
            /** Nickname */
            nickname: string;
            /** Password */
            password: string;
            /** Phone Token */
            phone_token: string;
            /** Student Number */
            student_number: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "STUDENT" | "TEACHER" | "ADMIN";
        /**
         * StaffInvitationAcceptRequest
         * @description Trade the single-use invitation token for a staff account (§5.8).
         */
        StaffInvitationAcceptRequest: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /**
         * StaffLoginRequest
         * @description Staff login: verified email + password + TOTP/recovery code (§5.8).
         */
        StaffLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Totp Code */
            totp_code: string;
        };
        /**
         * TokenPairResponse
         * @description One issued session (spec §5.6) — cookie-only refresh delivery.
         *
         *     The long-lived refresh token NEVER rides in the body:
         *     it travels exclusively in the HttpOnly refresh cookie the response
         *     sets, so a JSON body (loggers, proxies, XSS-readable storage) can
         *     never leak a live refresh credential. The body's ``access_token`` is
         *     the short-lived JWT — including the ``must_setup_totp`` pending staff
         *     session's, which is deliberate: it is not the long-lived credential
         *     and confined-by-construction to the TOTP setup endpoints.
         *     ``csrf_token`` mirrors the non-HttpOnly CSRF cookie so scripted
         *     clients can echo it without parsing ``Set-Cookie``.
         */
        TokenPairResponse: {
            /** Access Token */
            access_token: string;
            /** Csrf Token */
            csrf_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserPublic
         * @description Public account view returned to the account owner (spec §40).
         *
         *     The owner sees their own username/student number; no other surface
         *     exposes it. Status is included because ACTIVE (vs PENDING_PHONE)
         *     is the registration outcome clients branch on.
         */
        UserPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nickname */
            nickname: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Username */
            username: string;
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "PENDING_PHONE" | "ACTIVE" | "SUSPENDED" | "BANNED";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_forgot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordForgotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_phone_challenge_api_v1_auth_phone_challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_phone_challenge_api_v1_auth_phone_challenges__challenge_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneChallengeVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_student_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_staff_invitation_api_v1_auth_staff_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffInvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    staff_login_api_v1_auth_staff_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MePublic"];
                };
            };
        };
    };
    list_my_claims_api_v1_me_claims_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyClaimsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_email_verification_api_v1_me_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailBindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unbind_email_api_v1_me_email_unbind_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailUnbindRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_email_verification_api_v1_me_email_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_nickname_api_v1_me_nickname_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NicknameUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_phone_change_api_v1_me_phone_change_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_phone_change_api_v1_me_phone_change_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneChangeConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
