"""Immutable first-review revisions and public projection pointers."""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0031"
down_revision = "0030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_ie_evidence_identity", "ie_achievement_evidence", ["id", "achievement_id"]
    )
    op.create_table(
        "ie_achievement_revisions",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("creation_request_id", sa.Uuid(), nullable=False),
        sa.Column("creation_payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("project_version", sa.Integer(), nullable=False),
        sa.Column("achievement_version", sa.Integer(), nullable=False),
        sa.Column(
            "project_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "achievement_content",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "owner_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "operation IN ('SUBMIT','UPDATE')",
            name=op.f("ck_ie_achievement_revisions_operation"),
        ),
        sa.CheckConstraint(
            "char_length(creation_payload_fingerprint) = 64",
            name=op.f("ck_ie_achievement_revisions_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "number > 0 AND project_version > 0 AND achievement_version > 0",
            name=op.f("ck_ie_achievement_revisions_versions_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["ie_achievement_drafts.id"],
            name=op.f(
                "fk_ie_achievement_revisions_ie_achievement_drafts_achievement_id"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ie_achievement_revisions")),
        sa.UniqueConstraint(
            "achievement_id", "creation_request_id", name="uq_ie_revision_request"
        ),
        sa.UniqueConstraint("achievement_id", "number", name="uq_ie_revision_number"),
        sa.UniqueConstraint("id", "achievement_id", name="uq_ie_revision_identity"),
    )
    op.create_table(
        "ie_achievement_review_cases",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default="SUBMITTED", nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_request_id", sa.Uuid(), nullable=True),
        sa.Column("decision_payload_fingerprint", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "(status IN ('APPROVED','RETURNED')) = (decided_at IS NOT NULL) "
            "AND (status IN ('APPROVED','RETURNED')) = "
            "(decision_request_id IS NOT NULL)",
            name=op.f("ck_ie_achievement_review_cases_decision_state"),
        ),
        sa.CheckConstraint(
            "status <> 'RETURNED' OR (reason IS NOT NULL AND btrim(reason) <> '')",
            name=op.f("ck_ie_achievement_review_cases_return_reason"),
        ),
        sa.CheckConstraint(
            "status IN ('SUBMITTED','WITHDRAWN','APPROVED','RETURNED')",
            name=op.f("ck_ie_achievement_review_cases_status"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_ie_achievement_review_cases_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["ie_achievement_drafts.id"],
            name=op.f(
                "fk_ie_achievement_review_cases_ie_achievement_drafts_achievement_id"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"],
            ["users.id"],
            name=op.f("fk_ie_achievement_review_cases_users_assigned_user_id"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id", "achievement_id"],
            ["ie_achievement_revisions.id", "ie_achievement_revisions.achievement_id"],
            name="fk_ie_case_revision",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ie_achievement_review_cases")),
        sa.UniqueConstraint("revision_id", name="uq_ie_case_revision"),
    )
    op.create_index(
        "ix_ie_review_queue",
        "ie_achievement_review_cases",
        ["status", "submitted_at", "id"],
        unique=False,
    )
    op.create_index(
        "uq_ie_case_active",
        "ie_achievement_review_cases",
        ["achievement_id"],
        unique=True,
        postgresql_where=sa.text("status = 'SUBMITTED'"),
    )
    op.create_table(
        "ie_achievement_workflows",
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "first_review_state",
            sa.String(length=16),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column(
            "moderation_state",
            sa.String(length=16),
            server_default="NORMAL",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("public_revision_id", sa.Uuid(), nullable=True),
        sa.Column("first_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_update_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(first_review_state = 'APPROVED') = (public_revision_id IS NOT NULL) "
            "AND (first_review_state = 'APPROVED') = (first_approved_at IS NOT NULL) "
            "AND (first_review_state = 'APPROVED') = (latest_update_at IS NOT NULL)",
            name=op.f("ck_ie_achievement_workflows_public_state"),
        ),
        sa.CheckConstraint(
            "first_review_state IN ('DRAFT','SUBMITTED','RETURNED','APPROVED')",
            name=op.f("ck_ie_achievement_workflows_review_state"),
        ),
        sa.CheckConstraint(
            "moderation_state IN ('NORMAL','TAKEN_DOWN')",
            name=op.f("ck_ie_achievement_workflows_moderation_state"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_ie_achievement_workflows_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["ie_achievement_drafts.id"],
            name=op.f(
                "fk_ie_achievement_workflows_ie_achievement_drafts_achievement_id"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["public_revision_id", "achievement_id"],
            ["ie_achievement_revisions.id", "ie_achievement_revisions.achievement_id"],
            name="fk_ie_workflow_public_revision",
        ),
        sa.PrimaryKeyConstraint(
            "achievement_id", name=op.f("pk_ie_achievement_workflows")
        ),
    )
    op.create_table(
        "ie_revision_evidence",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("achievement_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "char_length(sha256) = 64", name=op.f("ck_ie_revision_evidence_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "achievement_id"],
            ["ie_achievement_evidence.id", "ie_achievement_evidence.achievement_id"],
            name="fk_ie_revision_evidence_material",
        ),
        sa.ForeignKeyConstraint(
            ["revision_id", "achievement_id"],
            ["ie_achievement_revisions.id", "ie_achievement_revisions.achievement_id"],
            name="fk_ie_revision_evidence_revision",
        ),
        sa.PrimaryKeyConstraint(
            "revision_id", "evidence_id", name=op.f("pk_ie_revision_evidence")
        ),
    )
    op.execute("""CREATE FUNCTION ie_immutable_revision() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
        RAISE EXCEPTION 'innovation revision is immutable'; END; $$""")
    op.execute("""CREATE TRIGGER ie_revision_immutable BEFORE UPDATE ON
        ie_achievement_revisions FOR EACH ROW
        EXECUTE FUNCTION ie_immutable_revision()""")
    op.execute("""CREATE TRIGGER ie_revision_evidence_immutable BEFORE UPDATE ON
        ie_revision_evidence FOR EACH ROW EXECUTE FUNCTION ie_immutable_revision()""")
    op.execute("""CREATE FUNCTION ie_guard_checked_evidence() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
        IF OLD.referenced AND (NOT NEW.referenced OR
            NEW.removed_at IS DISTINCT FROM OLD.removed_at)
        THEN RAISE EXCEPTION 'referenced evidence cannot be detached'; END IF;
        IF OLD.state = 'READY' AND
           ROW(NEW.object_key, NEW.content_type, NEW.size, NEW.sha256, NEW.state)
           IS DISTINCT FROM
           ROW(OLD.object_key, OLD.content_type, OLD.size, OLD.sha256, OLD.state)
        THEN RAISE EXCEPTION 'checked evidence is immutable'; END IF;
        RETURN NEW; END; $$""")
    op.execute("""CREATE TRIGGER ie_checked_evidence_immutable BEFORE UPDATE ON
        ie_achievement_evidence FOR EACH ROW
        EXECUTE FUNCTION ie_guard_checked_evidence()""")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER ie_checked_evidence_immutable ON ie_achievement_evidence")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ie_revision_evidence")
    op.drop_table("ie_achievement_workflows")
    op.drop_index(
        "uq_ie_case_active",
        table_name="ie_achievement_review_cases",
        postgresql_where=sa.text("status = 'SUBMITTED'"),
    )
    op.drop_index("ix_ie_review_queue", table_name="ie_achievement_review_cases")
    op.drop_table("ie_achievement_review_cases")
    op.drop_table("ie_achievement_revisions")
    op.drop_constraint(
        "uq_ie_evidence_identity", "ie_achievement_evidence", type_="unique"
    )
    op.execute("DROP FUNCTION ie_immutable_revision()")
    op.execute("DROP FUNCTION ie_guard_checked_evidence()")
    # ### end Alembic commands ###
